config/routes.rb
Rails.application.routes.draw do
  root to: 'book_search#index'
  post'search', to: 'book_search#search'
  resources :categories do
    resources :products
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
end

app/controllers/book_search_controller.rb
class BookSearchController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all.limit(12)
  end

  def search
    @products = Product.where("lower(title) LIKE ?", "%#{params[:keyword]}%")
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find_by(id: params[:category_id])
    @products = @category.products.all
    respond_to do |format|
      format.js
    end
  end

  def new

  end

  def show
    @category = Category.find_by(id: params[:category_id])
    @product = Product.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_search_helper.rb
module BookSearchHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/book_search/_index.html.erb
<% products.each do |product| %>
  <div class="product col">
    <img class="product-image" src="<%= product.image %>"/>
    <div class="product-title">
      <%=link_to product.title, category_product_path(product.category.id, product.id) %>
    </div>
  </div>
<% end %>

app/views/book_search/index.html.erb
<div class="left-content">
  <div id="id_categories">
    <h3>Category</h3>
    <div id="id_list_categories">
      <% @categories.each do |category| %>
          <%=link_to category.name, category_products_path(category.id), remote: true %>
        <br/>
      <% end %>
    </div>
  </div>
</div>
<div class="right-content">
  <div id="id_search_bar">
    <input type="text" placeholder="Enter Keyword" name="keyword" id="id_search">
    <div id="id_search_content"></div>
  </div>
  <div id="id_products_list">
    <%= render partial: 'index', locals: { products: @products} %>
  </div>
</div>

app/views/book_search/search.js.erb
$("#id_products_list").html("<%= escape_javascript(render partial: 'book_search/index', locals: { products: @products } ) %>");

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/index.js.erb
$("#id_products_list").html("<%= escape_javascript(render partial: 'book_search/index', locals: { products: @products } ) %>");

app/views/products/show.html.erb
<div class="container-product">
  <div>
    <div class="btn btn-back">
      <%= link_to "Back", root_path %>
    </div>
    <div>
      <%= image_tag @product.image  %>
    </div>
  </div>
  <table>
    <tr>
      <td class="col-type">Name:</td>
      <td class="col-product first-row">
        <div>
          <%= @product.title  %>
          ,
          <span>
            <%= @product.sub_title  %>
          </span>
        </div>
      </td>
    </tr>
    <tr>
      <td class="col-type">Price:</td>
      <td class="col-product">
        <div>
          <span>$</span>
          <%= @product.price %>
        </div>
      </td>
    </tr>
    <tr>r
      <td class="col-type">URL:</td>
      <td class="col-product">
        <a href="<%= @product.url%>", target="blank">
          <%= @product.url  %>
        </a>
      </td>
    </tr>
  </table>
</div>